### ISSUE TITLE
Не работает анонимное внесение правок

### ISSUE THREAD

**Issue by coding-future** [warodai/warodai.ru#6]
Сегодня в браузере Chrome версии 91.0.4472.164 попробовал отправить анонимную правку слова с сайта словаря https://warodai.ru/lookup/index.php, но появилось непонятное предупреждение "Подтвердите действие на странице warudai.ru: At least one email address must be verified to do that." В итоге правка не отправилась.

Когда залогинился в Github, всё отправилось без проблем.

Скриншот предупреждения: 
![image](https://user-images.githubusercontent.com/67520929/125948781-33a52311-a6a0-44cd-94b2-9272cfde2b75.png)

**Comment by nakendlom** [comment]
Да, действительно была проблема. Поправлено.
